doctrine:
    orm:
        # ...
        dql:
            string_functions:
                # Put these in application config.yml
                # ARRAYAGG         : Lighthart\GridBundle\DQL\Postgres\ArrayAgg
                # ARRAYAGGDISTINCT : Lighthart\GridBundle\DQL\Postgres\ArrayAggDistinct
                # REPLACE          : Lighthart\GridBundle\DQL\Postgres\ReplaceFunction
            numeric_functions:
            datetime_functions:
