doctrine:
    orm:
        # ...
        dql:
            string_functions:
                test_string: GridBundle\DQL\ArrayAggDistinctFunction
                test_string: GridBundle\DQL\ArrayAggFunction
                test_string: GridBundle\DQL\ReplaceFunction
            numeric_functions:
            datetime_functions:
