doctrine:
    orm:
        # ...
        dql:
            string_functions:
                test_string1: GridBundle\DQL\ArrayAggDistinctFunction
                test_string2: GridBundle\DQL\ArrayAggFunction
            numeric_functions:
            datetime_functions:
