services:
    grid.form.celltype:
        class: Lighthart\GridBundle\FormType\CellType
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]
        tags:
            - { name: form.type, alias: cell }