imports:
    - { resource: forms.yml }

# parameters:

services:
    lg.maker:
        class: Lighthart\GridBundle\Grid\GridMaker
        arguments: [ @doctrine, @router ]

    lg.subcookie.extension:
        class: Lighthart\GridBundle\Twig\SubcookieExtension
        tags:
            - { name: twig.extension }

    lg.boolean.extension:
        class: Lighthart\GridBundle\Twig\BooleanExtension
        tags:
            - { name: twig.extension }