imports:
    - { resource: forms.yml }

# parameters:

services:
    lg.maker:
        class: Lighthart\GridBundle\Grid\GridMaker
        arguments: [ @doctrine, @router, @lg.dumper ]

    lg.dumper:
            class: Lighthart\GridBundle\Grid\GridDumper
            arguments: [ @templating ]


    lg.subcookie.extension:
        class: Lighthart\GridBundle\Twig\SubcookieExtension
        tags:
            - { name: twig.extension }

    lg.boolean.extension:
        class: Lighthart\GridBundle\Twig\BooleanExtension
        arguments: [ @twig ]
        tags:
            - { name: twig.extension }

    lg.money.extension:
        class: Lighthart\GridBundle\Twig\MoneyExtension
        arguments: [ @twig ]
        tags:
            - { name: twig.extension }

    lg.csvtoarray.extension:
        class: Lighthart\GridBundle\Twig\CSVToArrayExtension
        arguments: [ @twig ]
        tags:
            - { name: twig.extension }