cell_edit :
    pattern      : /edit/{class}/{field}/{id}
    defaults     : { _controller: "LighthartGridBundle:Cell:edit" }
    requirements :
        class : \w+
        field : \w+
        id    : \d+

cell_value :
    pattern      : /value/{class}/{field}/{id}
    defaults     : { _controller: "LighthartGridBundle:Cell:value" }
    requirements :
        class : \w+
        field : \w+
        id    : \d+

cell_update :
    pattern      : /update/{class}/{field}/{id}
    defaults     : { _controller: "LighthartGridBundle:Cell:update" }
    requirements :
        class   : \w+
        field   : \w+
        id      : \d+
        _method : post