grid_index :
    pattern      : /
    defaults     : { _controller: "LighthartGridBundle:Grid:index" }

entity_grid :
    pattern      : /entityGrid/{class}/
    defaults     : { _controller: "LighthartGridBundle:Grid:entityGrid" }
    requirements :
        class : \w+
        field : \w+
