grid_index :
    pattern      : /
    defaults     : { _controller: "LighthartGridBundle:Grid:index" }

grid :
    pattern      : /entity/{class}/
    defaults     : { _controller: "LighthartGridBundle:Grid:grid" }
    requirements :
        class : \w+
        field : \w+